[project]
name = "research-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "mcp>=1.6.0",
  "beautifulsoup4>=4.13.3",
  "httpx>=0.28.1"
]
